### ISSUE TITLE
Minimum CMake version

### ISSUE THREAD

**Issue by ethanbb** [open-ephys-plugins/OEPlugin#1]
Here and in CMake build files in other repos here, the minimum CMake version should be at least 3.13.0, as this is the release that introduced the `target_link_directories` command.

**Comment by aacuevas** [comment]
Ah true.

I started developing this on Windows, with the latest CMake version. The issue is that many supported linux distributions are stuck with 3.5 so I modified everything else to fit that version but it seems I forgot those lines, as they are only executed on Windows.

I'll just move the paths to the following `target_link_libraries(${PLUGIN_NAME} open-ephys.lib)` line so the path is absolute, they are needed only for that.

**Comment by ethanbb** [comment]
OK, makes sense.
